### ISSUE TITLE
SynthModule

### ISSUE THREAD

**Issue by maxsolomonhenry** [turian/ddsp-drum#14]
Not sure what the SynthModule class is doing anymore.

The original idea is this: SynthModule holds the sample rate and control rate. All other modules inherit from that. It's also responsible for converting from sample to control rate. Clean.

At the moment it's almost completely redundant. It happens to do rate conversion, but that's not always needed. Plus all of the modules manually inherit the rates from globals by default. Feels really sloppy to me. 

Either we go back to how it was, or we axe this class and move `control_to_sample_rate` to util.py

**Comment by jorshi** [comment]
Weren't we talking about having sample rate be a parameter for SynthModule? And having the default value be the that global rate? How about we make SynthModule be an abstract base class set up with sample rate like that and then the __call__ function (or forward?) be an abstractmethod that needs to be defined in any child class. That way we enforce the structure all inheriting classes.

Also. I thought we were going to do away with the different rates between control signals and the audio sample rate?

**Comment by maxsolomonhenry** [comment]
I agree we should nix the control rate. I'd be happy to do that in another branch.

**Comment by turian** [comment]
Agree on removing control_rate.

Also we could use a modulefactory pattern later if we want: https://stackoverflow.com/questions/65616989/pattern-for-ensuring-all-modules-have-same-parameters
