### ISSUE TITLE
ADSR behaviour

### ISSUE THREAD

**Issue by maxsolomonhenry** [turian/ddsp-drum#15]
The adsr is not quite acting as a real midi instrument right now. This was a design oversight on my part.

As is (what you might call "one-shot trigger" behaviour):

(1) note on --> trigger ALL of attack and decay.
(2) sustain (at "sustain" value) for some predetermined duration
(3) note off --> trigger release from "sustain" value to 0.

In a synthesizer use case:

(1) note on --> step through attack and decay **for as long as you hold note on**.
i.e., a=0.5, d=0.5. if you hold the note for 0.75s, you get the full attack (0.5s) and **only 0.25s of decay**.

(2) if you happen to hold for longer than a + d, then it sustains at the "sustain" value.

(3) note off --> decay from **whatever the envelope value happens to be at** to 0.

Should we implement this or not?

**Comment by jorshi** [comment]
I like that idea. In this context would we just need note on length since it isn't real time?

**Comment by maxsolomonhenry** [comment]
Yeah, we'd specify "note on length." So if you hold a note for 1 second, with a=0.25, d=0.25, r=0.5, you'd get a signal thats 1.5 seconds long

**Comment by maxsolomonhenry** [comment]
@turian ? What say you? I could attack this as well.
