### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by jorshi** [turian/ddsp-drum#23]
Some code might not make sense to include in the examples for tests. Do we want some more formal tests so we can maintain solid code coverage? Especially if this is being checked when making new PRs?

**Comment by maxsolomonhenry** [comment]
I had a similar thought. I'm for it.

Though I appreciate maintaining a running examples notebook. I find it helpful to get to know the changes quickly.

**Comment by jorshi** [comment]
Implemented in pr #31
