### ISSUE TITLE
parameter min_max ranges

### ISSUE THREAD

**Issue by maxsolomonhenry** [turian/ddsp-drum#27]
We might want to have a look at these. A 20s max for attack time is pretty extreme. It doesn't give you a lot of room for nuance in that 0-1 normalized range. At least from a human perspective.

Especially in a drum machine, you want lots of granularity around very short attack times (like the quick pitch "whip" at the attack of a drum hit).

**Comment by turian** [comment]
@maxsolomonhenry That suggests we should just use a different curve? So that 0 - 0.5 is like 0 to 1 for attack, and then 0.5 to 1.0 is like 1 to 20?

**Comment by maxsolomonhenry** [comment]
More like max attack time should be AT MOST 2 seconds. Even that is extremely long

**Comment by turian** [comment]
@maxsolomonhenry I'm fine with that
