### ISSUE TITLE
Randomization of parameters should not change the duration of the sound

### ISSUE THREAD

**Issue by turian** [turian/ddsp-drum#46]
See https://github.com/turian/ddsp-drum/pull/42

@jorshi proposes a hyperparameter which is the sound length.

**Comment by maxsolomonhenry** [comment]
The question is, at what level to we want to manage this? We could mange it on the Drum itself, or maybe on the Synth class it inherits. We're already doing envelope length management module.py (L594).

Would be two lines of code to fix. But then we wouldn't be able to backprop envelopes on individually, which would make unit tests difficult.

So it could be done at the ADSR level. Too.

**Comment by maxsolomonhenry** [comment]
^ resolved.
