### ISSUE TITLE
VCO should have a pitch parameter?

### ISSUE THREAD

**Issue by turian** [turian/ddsp-drum#6]
@maxsolomonhenry writes: "Now that you say this, it makes me think the VCO should have a base f0 parameter, though.

i.e. --> learn the following parameters:

pitch envelope: a, d, s, r, alpha. --> this is multiplied by a depth argument --> then into the VCO where its added to the f0 in there ---> VCO: f0"

https://github.com/turian/ddsp-drum/pull/3#discussion_r547558308

**Comment by maxsolomonhenry** [comment]
good idea. it has one now.
